"""Added title and subtitle

Revision ID: 8febdb894526
Revises: a3391339c722
Create Date: 2021-07-18 14:54:03.007088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8febdb894526'
down_revision = 'a3391339c722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=128), nullable=True))
    op.add_column('post', sa.Column('subtitle', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'subtitle')
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
