"""Added banner picture URL path to Post

Revision ID: dbd88a0a4ad0
Revises: a31862f69840
Create Date: 2021-07-18 20:58:49.432185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd88a0a4ad0'
down_revision = 'a31862f69840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('banner_picture_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'banner_picture_path')
    # ### end Alembic commands ###
